"""Frozen interfaces (Build Plan Section 4).

Application code (ingestion, answer, surfaces, governance) depends only on
these Protocols. Concrete engines live in ``adapters/`` and are swapped by
configuration, never by editing application code. Every method is
tenant-scoped: ``tenant`` is a required argument on every call that touches
tenant data (invariant I5).
"""
from __future__ import annotations

from typing import Any, Optional, Protocol, runtime_checkable

from .types import (
    Answer, Candidate, ConvertedDocument, GraphEdge, GraphNode, Job,
    Passage, PolicyResult, Principal, Provenance, RawItem,
)


@runtime_checkable
class ObjectStore(Protocol):
    """Immutable blob storage for originals, keyed by content hash (I8)."""
    def put(self, tenant: str, content_hash: str, data: bytes, meta: dict) -> str: ...
    def get(self, tenant: str, content_hash: str) -> bytes: ...
    def exists(self, tenant: str, content_hash: str) -> bool: ...
    def url(self, tenant: str, content_hash: str) -> str: ...


@runtime_checkable
class Queue(Protocol):
    """Durable, transactional job queue with retries and dead-letter."""
    def enqueue(self, tenant: str, job: Job) -> str: ...
    def lease(self, worker: str, ttl_s: float = 30.0) -> Optional[Job]: ...
    def ack(self, job_id: str) -> None: ...
    def nack(self, job_id: str, reason: str) -> None: ...
    def deadletter(self, job_id: str, reason: str) -> None: ...
    def depth(self) -> int: ...


@runtime_checkable
class IdentityProvider(Protocol):
    """Resolves the caller and their scopes (Section 12)."""
    def authenticate(self, credentials: dict) -> Principal: ...
    def mint(self, principal: Principal) -> str: ...  # issue a signed token (local IdP)


@runtime_checkable
class ModelClient(Protocol):
    """Provider-agnostic LLM invocation with tier + budget awareness (I4, I12).

    Tiers: ``fast`` | ``deep`` | ``escalation``. A provider swap must never
    change embeddings (I9).
    """
    def complete(self, tenant: str, tier: str, messages: list[dict], opts: dict) -> dict: ...
    def available(self) -> bool: ...


@runtime_checkable
class Embedder(Protocol):
    """Text -> vector. Self-hosted, deterministic, versioned (I9)."""
    def embed(self, texts: list[str]) -> list[list[float]]: ...
    def model_id(self) -> str: ...
    def dim(self) -> int: ...


@runtime_checkable
class VectorIndex(Protocol):
    def upsert(self, tenant: str, items: list[dict]) -> None: ...
    def search(self, tenant: str, query_vec: list[float], k: int, acl: list[str]) -> list[tuple[str, float]]: ...
    def delete(self, tenant: str, ids: list[str]) -> None: ...


@runtime_checkable
class LexicalIndex(Protocol):
    def index(self, tenant: str, passages: list[Passage]) -> None: ...
    def search(self, tenant: str, query: str, k: int, acl: list[str]) -> list[tuple[str, float]]: ...
    def delete(self, tenant: str, ids: list[str]) -> None: ...


@runtime_checkable
class GraphStore(Protocol):
    def upsert_nodes(self, tenant: str, nodes: list[GraphNode]) -> None: ...
    def upsert_edges(self, tenant: str, edges: list[GraphEdge]) -> None: ...
    def neighbors(self, tenant: str, node_id: str, hops: int) -> list[GraphEdge]: ...
    def resolve(self, tenant: str, mention: str, type_: str) -> Optional[GraphNode]: ...


@runtime_checkable
class Connector(Protocol):
    """Source-system adapter emitting canonical records. Read-only (I13)."""
    def discover(self, config: dict) -> dict: ...
    def pull(self, cursor: Optional[str]) -> tuple[list[RawItem], Optional[str]]: ...
    def scopes(self) -> list[str]: ...


@runtime_checkable
class DocumentConverter(Protocol):
    """bytes + type -> pages/regions/passages with provenance."""
    def convert(self, raw: RawItem) -> ConvertedDocument: ...
    def supports(self, mime: str) -> bool: ...


@runtime_checkable
class Telemetry(Protocol):
    def span(self, name: str, attrs: dict) -> "SpanCtx": ...
    def record(self, name: str, attrs: dict) -> None: ...


class SpanCtx(Protocol):
    trace_id: str
    def __enter__(self) -> "SpanCtx": ...
    def __exit__(self, *exc) -> None: ...
    def set(self, **attrs) -> None: ...


@runtime_checkable
class PolicyEngine(Protocol):
    def check(self, principal: Principal, action: str, context: dict) -> PolicyResult: ...
    def budget_remaining(self, tenant: str) -> float: ...


@runtime_checkable
class EvalGate(Protocol):
    def evaluate(self, tenant: str, candidate_version: int) -> dict: ...
